-- V29__sync_divida_categoria_to_transacao.sql
-- Synchronize categoria_id from divida to existing transacao records generated by paid debt installments
UPDATE transacao t
SET categoria_id = d.categoria_id
FROM parcela_divida pd
JOIN divida d ON pd.divida_id = d.id
WHERE pd.transacao_id = t.id
  AND d.categoria_id IS NOT NULL;
